/**
 * The icons offered in the category editor, grouped and tagged for search.
 *
 * This module is loaded on demand (see CategoryIcon's `loadIconCatalog`):
 * each Phosphor icon carries all six weights, so bundling ~150 of them up
 * front would add about 40% to the main chunk for a picker most sessions
 * never open.
 */
import type { ComponentType } from "react";
import {
  AirplaneTakeoff,
  AirplaneTilt,
  Armchair,
  Avocado,
  Baby,
  BabyCarriage,
  Backpack,
  Balloon,
  Bandaids,
  Bank,
  Barbell,
  Basket,
  Basketball,
  Bathtub,
  Bed,
  BeerBottle,
  BeerStein,
  Bicycle,
  Bird,
  Boat,
  BookOpen,
  Book,
  Books,
  Boot,
  BowlFood,
  BowlSteam,
  Brain,
  Brandy,
  Bread,
  Briefcase,
  Broom,
  Buildings,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarProfile,
  Carrot,
  Cat,
  Chalkboard,
  Champagne,
  ChargingStation,
  ChartLineUp,
  Cheese,
  Church,
  Cigarette,
  Cloud,
  Code,
  Coffee,
  CoffeeBean,
  Coins,
  Compass,
  Confetti,
  Cookie,
  CookingPot,
  Couch,
  CreditCard,
  CurrencyDollar,
  CurrencyEur,
  Desktop,
  DeviceMobile,
  Diamond,
  Dog,
  Dress,
  Drop,
  Egg,
  Envelope,
  Eyeglasses,
  FilmSlate,
  FirstAid,
  FirstAidKit,
  Fish,
  FishSimple,
  Flag,
  Flame,
  Flower,
  ForkKnife,
  GameController,
  GasPump,
  Gear,
  Gift,
  Globe,
  Golf,
  GraduationCap,
  Grains,
  Guitar,
  Hamburger,
  Hammer,
  HandCoins,
  HandHeart,
  Handbag,
  Handshake,
  Headphones,
  Heart,
  Heartbeat,
  HighHeel,
  Hoodie,
  Hospital,
  House,
  HouseLine,
  IceCream,
  Invoice,
  Island,
  Key,
  Keyboard,
  Lamp,
  Laptop,
  Leaf,
  Lightbulb,
  Lightning,
  MapPin,
  MapTrifold,
  Martini,
  MaskHappy,
  Microphone,
  Money,
  MonitorPlay,
  Moon,
  Motorcycle,
  Mountains,
  MusicNote,
  MusicNotes,
  Newspaper,
  Notebook,
  OrangeSlice,
  Package,
  PaintBrush,
  PaintRoller,
  Palette,
  Pants,
  PawPrint,
  Pencil,
  Pepper,
  Percent,
  PersonSimpleBike,
  PersonSimpleRun,
  PersonSimpleSwim,
  Phone,
  PianoKeys,
  PiggyBank,
  Pill,
  PintGlass,
  Pizza,
  Plant,
  Plug,
  Popcorn,
  Printer,
  PuzzlePiece,
  Question,
  Receipt,
  Recycle,
  Robot,
  Rocket,
  Sailboat,
  Scales,
  Scissors,
  Scooter,
  ShieldCheck,
  ShoppingBag,
  ShoppingBagOpen,
  ShoppingCart,
  ShoppingCartSimple,
  Shrimp,
  Smiley,
  Sneaker,
  Snowflake,
  SoccerBall,
  Sock,
  Sparkle,
  SprayBottle,
  Star,
  Stethoscope,
  Storefront,
  Student,
  Subway,
  Suitcase,
  SuitcaseRolling,
  Sun,
  Sunglasses,
  SwimmingPool,
  Syringe,
  TShirt,
  Tag,
  Taxi,
  Television,
  TennisBall,
  Tent,
  Thermometer,
  Ticket,
  Toilet,
  Toolbox,
  Tooth,
  Train,
  Tram,
  Trophy,
  Truck,
  Umbrella,
  User,
  UsersThree,
  Van,
  Volleyball,
  Wallet,
  WashingMachine,
  Watch,
  WifiHigh,
  Wine,
  Wrench,
  type IconProps,
} from "@phosphor-icons/react";

export interface CatalogIcon {
  name: string;
  group: string;
  /** Extra search words; the name itself is always searchable. */
  tags: string[];
  Icon: ComponentType<IconProps>;
}

type Entry = [Icon: ComponentType<IconProps>, name: string, tags: string];

const GROUPS: [group: string, entries: Entry[]][] = [
  ["Food & drink", [
    [Pizza, "Pizza", "food takeaway delivery"],
    [Hamburger, "Hamburger", "burger fast food"],
    [ForkKnife, "ForkKnife", "restaurant dining eat out meal"],
    [BowlFood, "BowlFood", "noodles ramen asian lunch"],
    [BowlSteam, "BowlSteam", "soup hot meal"],
    [CookingPot, "CookingPot", "cooking home meal"],
    [Bread, "Bread", "bakery breakfast"],
    [Cake, "Cake", "dessert bakery birthday"],
    [Cookie, "Cookie", "snack sweets"],
    [IceCream, "IceCream", "dessert sweets"],
    [Popcorn, "Popcorn", "snack cinema"],
    [Carrot, "Carrot", "vegetables produce healthy"],
    [OrangeSlice, "OrangeSlice", "fruit produce"],
    [Avocado, "Avocado", "produce healthy"],
    [Pepper, "Pepper", "vegetables produce"],
    [Cheese, "Cheese", "dairy deli"],
    [Egg, "Egg", "breakfast"],
    [FishSimple, "FishSimple", "seafood fish market"],
    [Shrimp, "Shrimp", "seafood"],
    [Grains, "Grains", "bulk rice cereal"],
    [Coffee, "Coffee", "cafe latte espresso"],
    [CoffeeBean, "CoffeeBean", "coffee beans roastery"],
    [BeerBottle, "BeerBottle", "drinks bar alcohol"],
    [BeerStein, "BeerStein", "pub drinks"],
    [PintGlass, "PintGlass", "pub pint drinks"],
    [Wine, "Wine", "drinks alcohol"],
    [Martini, "Martini", "cocktail bar"],
    [Champagne, "Champagne", "celebration party"],
    [Brandy, "Brandy", "spirits whisky"],
  ]],
  ["Shopping", [
    [ShoppingCart, "ShoppingCart", "groceries supermarket"],
    [ShoppingCartSimple, "ShoppingCartSimple", "groceries cart"],
    [ShoppingBag, "ShoppingBag", "shopping retail"],
    [ShoppingBagOpen, "ShoppingBagOpen", "shopping purchase"],
    [Basket, "Basket", "market groceries"],
    [Storefront, "Storefront", "shop store local"],
    [Tag, "Tag", "sale discount price"],
    [Package, "Package", "delivery parcel online order"],
    [TShirt, "TShirt", "clothes clothing apparel"],
    [Dress, "Dress", "clothes clothing fashion"],
    [Pants, "Pants", "clothes clothing trousers"],
    [Hoodie, "Hoodie", "clothes clothing sweater"],
    [Sock, "Sock", "clothes underwear"],
    [Sneaker, "Sneaker", "shoes trainers"],
    [Boot, "Boot", "shoes"],
    [HighHeel, "HighHeel", "shoes fashion"],
    [Handbag, "Handbag", "bag accessories"],
    [Backpack, "Backpack", "bag school"],
    [Watch, "Watch", "jewelry accessories"],
    [Sunglasses, "Sunglasses", "accessories"],
    [Eyeglasses, "Eyeglasses", "glasses optician"],
    [Diamond, "Diamond", "jewelry luxury"],
  ]],
  ["Home & bills", [
    [House, "House", "home rent mortgage"],
    [HouseLine, "HouseLine", "home housing"],
    [Buildings, "Buildings", "apartment flat rent"],
    [Key, "Key", "rent deposit keys"],
    [Bed, "Bed", "furniture bedroom hotel"],
    [Couch, "Couch", "furniture living room"],
    [Armchair, "Armchair", "furniture"],
    [Lamp, "Lamp", "furniture lighting decor"],
    [Bathtub, "Bathtub", "bathroom"],
    [Toilet, "Toilet", "bathroom toiletries"],
    [Broom, "Broom", "cleaning household"],
    [SprayBottle, "SprayBottle", "cleaning supplies"],
    [WashingMachine, "WashingMachine", "laundry appliances"],
    [Hammer, "Hammer", "diy repairs"],
    [Wrench, "Wrench", "repairs maintenance"],
    [Toolbox, "Toolbox", "tools diy"],
    [PaintRoller, "PaintRoller", "renovation decorating"],
    [Plant, "Plant", "plants garden"],
    [Flower, "Flower", "flowers garden florist"],
    [Plug, "Plug", "utilities electricity power"],
    [Lightbulb, "Lightbulb", "electricity energy"],
    [Lightning, "Lightning", "electricity energy power"],
    [Drop, "Drop", "water utilities"],
    [Flame, "Flame", "gas heating"],
    [Thermometer, "Thermometer", "heating temperature"],
    [WifiHigh, "WifiHigh", "internet broadband"],
    [Receipt, "Receipt", "bills receipt"],
    [Invoice, "Invoice", "bills invoice"],
  ]],
  ["Transport & travel", [
    [Car, "Car", "car vehicle"],
    [CarProfile, "CarProfile", "car vehicle"],
    [GasPump, "GasPump", "fuel petrol gas"],
    [ChargingStation, "ChargingStation", "ev electric car charging"],
    [Taxi, "Taxi", "cab uber ride"],
    [Bus, "Bus", "public transport"],
    [Train, "Train", "rail public transport"],
    [Subway, "Subway", "metro tube underground"],
    [Tram, "Tram", "public transport"],
    [Bicycle, "Bicycle", "bike cycling"],
    [Scooter, "Scooter", "scooter kick"],
    [Motorcycle, "Motorcycle", "motorbike"],
    [Van, "Van", "moving rental"],
    [Truck, "Truck", "moving delivery"],
    [Boat, "Boat", "ferry"],
    [Sailboat, "Sailboat", "sailing boat"],
    [AirplaneTilt, "AirplaneTilt", "flight travel"],
    [AirplaneTakeoff, "AirplaneTakeoff", "flight travel airport"],
    [Suitcase, "Suitcase", "luggage travel trip"],
    [SuitcaseRolling, "SuitcaseRolling", "luggage travel holiday"],
    [MapTrifold, "MapTrifold", "trip sightseeing"],
    [MapPin, "MapPin", "place location"],
    [Globe, "Globe", "international world"],
    [Compass, "Compass", "adventure"],
    [Tent, "Tent", "camping outdoors"],
    [Mountains, "Mountains", "hiking outdoors"],
    [Island, "Island", "holiday vacation beach"],
    [Umbrella, "Umbrella", "beach insurance"],
  ]],
  ["Health & sport", [
    [Heart, "Heart", "love health"],
    [Heartbeat, "Heartbeat", "health medical"],
    [FirstAid, "FirstAid", "health medical"],
    [FirstAidKit, "FirstAidKit", "pharmacy medicine"],
    [Pill, "Pill", "medicine pharmacy"],
    [Syringe, "Syringe", "vaccine doctor"],
    [Stethoscope, "Stethoscope", "doctor medical"],
    [Hospital, "Hospital", "hospital medical"],
    [Tooth, "Tooth", "dentist dental"],
    [Bandaids, "Bandaids", "pharmacy"],
    [Brain, "Brain", "therapy mental health"],
    [Barbell, "Barbell", "gym fitness"],
    [PersonSimpleRun, "PersonSimpleRun", "running fitness"],
    [PersonSimpleBike, "PersonSimpleBike", "cycling fitness"],
    [PersonSimpleSwim, "PersonSimpleSwim", "swimming"],
    [SwimmingPool, "SwimmingPool", "swimming pool"],
    [SoccerBall, "SoccerBall", "football sport"],
    [Basketball, "Basketball", "sport"],
    [TennisBall, "TennisBall", "tennis padel sport"],
    [Volleyball, "Volleyball", "sport"],
    [Golf, "Golf", "sport"],
    [Trophy, "Trophy", "competition"],
  ]],
  ["Fun & culture", [
    [Television, "Television", "tv streaming subscriptions"],
    [MonitorPlay, "MonitorPlay", "streaming video"],
    [FilmSlate, "FilmSlate", "cinema movies film"],
    [Ticket, "Ticket", "tickets events concert"],
    [MaskHappy, "MaskHappy", "theatre shows"],
    [GameController, "GameController", "games gaming"],
    [PuzzlePiece, "PuzzlePiece", "games hobbies"],
    [MusicNote, "MusicNote", "music song"],
    [MusicNotes, "MusicNotes", "music concerts"],
    [Headphones, "Headphones", "music audio podcast"],
    [Microphone, "Microphone", "karaoke podcast"],
    [Guitar, "Guitar", "music instrument"],
    [PianoKeys, "PianoKeys", "music lessons"],
    [Palette, "Palette", "art hobbies"],
    [PaintBrush, "PaintBrush", "art crafts"],
    [Camera, "Camera", "photography"],
    [Book, "Book", "books reading"],
    [Books, "Books", "books reading library"],
    [BookOpen, "BookOpen", "books reading"],
    [Newspaper, "Newspaper", "news magazine subscription"],
    [Confetti, "Confetti", "party celebration"],
    [Balloon, "Balloon", "party birthday"],
    [Gift, "Gift", "gifts presents"],
  ]],
  ["Tech & money", [
    [DeviceMobile, "DeviceMobile", "phone mobile plan"],
    [Phone, "Phone", "phone call"],
    [Laptop, "Laptop", "computer"],
    [Desktop, "Desktop", "computer"],
    [Keyboard, "Keyboard", "computer accessories"],
    [Printer, "Printer", "office supplies"],
    [Cloud, "Cloud", "cloud storage software"],
    [Code, "Code", "software apps"],
    [Robot, "Robot", "ai software"],
    [CreditCard, "CreditCard", "card payment"],
    [Wallet, "Wallet", "cash wallet"],
    [Bank, "Bank", "bank fees"],
    [Money, "Money", "cash"],
    [Coins, "Coins", "cash change"],
    [CurrencyDollar, "CurrencyDollar", "money dollar"],
    [CurrencyEur, "CurrencyEur", "money euro"],
    [PiggyBank, "PiggyBank", "savings"],
    [HandCoins, "HandCoins", "loan lending debt"],
    [ChartLineUp, "ChartLineUp", "investments stocks"],
    [Percent, "Percent", "interest tax"],
    [Calculator, "Calculator", "tax accounting"],
    [Scales, "Scales", "legal lawyer"],
    [ShieldCheck, "ShieldCheck", "insurance"],
  ]],
  ["People, work & study", [
    [Briefcase, "Briefcase", "work business"],
    [Handshake, "Handshake", "business clients"],
    [GraduationCap, "GraduationCap", "education school university tuition"],
    [Student, "Student", "school student"],
    [Chalkboard, "Chalkboard", "classes lessons"],
    [Notebook, "Notebook", "stationery school"],
    [Pencil, "Pencil", "stationery"],
    [Baby, "Baby", "baby kids childcare"],
    [BabyCarriage, "BabyCarriage", "baby stroller"],
    [UsersThree, "UsersThree", "family friends group"],
    [User, "User", "personal"],
    [HandHeart, "HandHeart", "charity donation"],
    [Church, "Church", "religion donation"],
    [Dog, "Dog", "pets dog"],
    [Cat, "Cat", "pets cat"],
    [PawPrint, "PawPrint", "pets vet"],
    [Bird, "Bird", "pets"],
    [Fish, "Fish", "pets aquarium"],
    [Scissors, "Scissors", "haircut barber salon"],
    [Envelope, "Envelope", "post mail"],
    [Calendar, "Calendar", "events appointments"],
  ]],
  ["Other", [
    [Star, "Star", "favorite"],
    [Sparkle, "Sparkle", "special treat"],
    [Smiley, "Smiley", "fun"],
    [Sun, "Sun", "summer"],
    [Moon, "Moon", "night"],
    [Snowflake, "Snowflake", "winter"],
    [Leaf, "Leaf", "eco nature"],
    [Recycle, "Recycle", "eco"],
    [Cigarette, "Cigarette", "smoking tobacco"],
    [Gear, "Gear", "settings misc"],
    [Rocket, "Rocket", "projects"],
    [Flag, "Flag", "goals"],
    [Question, "Question", "misc other unknown"],
  ]],
];

export const ICON_CATALOG: CatalogIcon[] = GROUPS.flatMap(([group, entries]) =>
  entries.map(([Icon, name, tags]) => ({ name, group, tags: tags.split(" "), Icon })),
);

export const ICON_GROUPS = GROUPS.map(([group]) => group);

/**
 * Every query word must start one of the icon's words (name, group or tags):
 * "shopping cart" finds ShoppingCart, "gym" finds Barbell, and "sport" finds
 * sports icons without matching "transport".
 */
export function searchIcons(query: string, icons: CatalogIcon[] = ICON_CATALOG): CatalogIcon[] {
  const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (!words.length) return icons;
  return icons.filter((icon) => {
    const hay = [icon.name.replace(/([a-z])([A-Z])/g, "$1 $2"), icon.group, ...icon.tags]
      .join(" ")
      .toLowerCase()
      .split(/[^a-z0-9]+/);
    return words.every((w) => hay.some((h) => h.startsWith(w)));
  });
}
